### ISSUE TITLE
SetBaseFactionRank seems to work unreliable

### ISSUE THREAD

**Issue by Just0Chill** [jazzisparis/JIP-LN-NVSE#20]
Hey there jazzisparis,

thanks again for your help back in 2017.
https://forums.nexusmods.com/index.php?/topic/2619794-jip-nvse-plugin/page-127#entry53930538
;)

Anyways, I somewhat had issues with the command back these days and ultimately decided to stick to the scanning method.
However, as of recently coming back to it, I made a pretty configurable version which still has the same issues with SetBaseFactionRank.
https://geckwiki.com/index.php?title=SetBaseFactionRank

I've recorded a video to showcase the issue:
https://www.youtube.com/watch?v=cGvXXYa40TA

As you can see the Den Mother reacts accurately on it (possibly a placed reference), while the spawns appear a bit tricky.
They often do not react to immediate faction changes on their base form.
Except reloading fixes the issue.

Is it possible to fix that behaviour on the function so it's a bit more dynamic?
I've checked the Nightstalkers that do not react properly and they simply don't get added into the faction.
"GetInFaction" returns 0.
When reloading it returns 1 and they behave properly. :O

Kindest regards,
JC

**Comment by Just0Chill** [comment]
Ah, sorry for forgetting some important infos. :(
I am using
xNVSE 6.2.5
and JIP 56.50.

**Comment by jazzisparis** [comment]
This should be fixed as of version 56.54.
