### ISSUE TITLE
ModifyPositiveChemDuration Fix not showing in Pip Boy

### ISSUE THREAD

**Issue by KenJyn76** [jazzisparis/JIP-LN-NVSE#29]
I had a bit of a tough time hunting this one down -- this plugin changes the ModifyPositiveChemDuration script to only work on chems, and not food items. Ideally, I'd prefer a function like that to be optional, if at all possible, but if that's not in line with the project's goals or identity, is it possible to fix the Pip Boy display? Food items still show an increased duration with the script fixed, but the applied effect is still shortened. This makes the function appear to be a bug. It took me a while to hunt this down, because it doesn't appear to be documented anywhere besides a comment on the Nexus Page, and on the YUP page. Are all the fixes in this plugin documented anywhere? 

Thank you

**Comment by jazzisparis** [comment]
Fixed in v56.90
