### ISSUE TITLE
GetEncumbranceRate does not account Perk Entry 22

### ISSUE THREAD

**Issue by Demorome** [jazzisparis/JIP-LN-NVSE#4]
(Perk Entry 22 = ["Get Max Carry Weight"](https://geckwiki.com/index.php?title=GetPerkModifier))

When calling GetEncumbranceRate on the player before and after adding a test perk that adds 5.0 to the max carry weight (see image below), I noticed no difference in the ratio, meaning the increase in max carry weight is not being accounted.
![image](https://user-images.githubusercontent.com/69116996/116790617-92807400-aa8b-11eb-832b-5e21dde204e4.png)

Code from GetPerkModifier could be used to fix this issue.

**Comment by jazzisparis** [comment]
Fixed.
