### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by PopeRigby** [jazzisparis/JIP-LN-NVSE#9]
Would it be feasible for you to publish the latest releases to GitHub as well as Nexus Mods? You could even setup GitHub CI to do it for you. I'm a contributor on a command line mod manager, [Portmod](https://gitlab.com/portmod/portmod), and it would make it a lot more seamless for the user if Portmod was able to just grab it from the direct GitHub link, instead of having to go to Nexus Mods, and go through the "Slow" button to download the file.

**Comment by jazzisparis** [comment]
Done. Thanks for the suggestion.

**Comment by PopeRigby** [comment]
Thanks (:
